const actionType = {
    USER_LOGIN_LOADING : "USER_LOGIN_LOADING",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_ERROR : "USER_LOGIN_ERROR",
    USER_SET_TOKEN : "USER_SET_TOKEN",
    USER_INFO : "USER_INFO",
    TOP_LATEST_BLOG : "TOP_LATEST_BLOG",
    TOP_FIVE_LATEST_BLOG : "TOP_FIVE_LATEST_BLOG"
}


export default actionType