const actionType = {
    USER_LOGIN_LOADING : "USER_LOGIN_LOADING",
    USER_LOGIN_SUCCESS : "USER_LOGIN_SUCCESS",
    USER_LOGIN_ERROR : "USER_LOGIN_ERROR",
    USER_SET_TOKEN : "USER_SET_TOKEN",
    USER_SET_IS_USER_AUTH : "USER_SET_IS_USER_AUTH"
}


export default actionType